{
 "title": "Web-Vitals-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "822f9856", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "browser_Instrumentation" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "FID Summary",
     "type": "stat",
     "description": "To provide a good user experience, sites should strive to have a First Input Delay of 100 milliseconds or less. ",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(Web_Vitals{name=\"FID\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FID P75",
     "type": "timeseries",
     "description": "To ensure you're hitting this target for most of your users, a good threshold to measure is the 75th percentile of page loads, segmented across mobile and desktop devices.",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 9 },
     "targets": [
      {
       "expr": "quantile(0.75, Web_Vitals{name=\"FID\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FID Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "Web_Vitals{name=\"FID\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "LCP Summary",
     "type": "stat",
     "description": "To provide a good user experience, sites should strive to have LCP of 2.5 seconds or less. ",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(Web_Vitals{name=\"LCP\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LCP P75",
     "type": "timeseries",
     "description": "To ensure you're hitting this target for most of your users, a good threshold to measure is the 75th percentile of page loads, segmented across mobile and desktop devices.",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 24 },
     "targets": [
      {
       "expr": "quantile(0.75, Web_Vitals{name=\"LCP\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LCP Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "Web_Vitals{name=\"LCP\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CLS Summary",
     "type": "stat",
     "description": "To provide a good user experience, a site must have a CLS score of 0.1 or less",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(Web_Vitals{name=\"CLS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CLS P75",
     "type": "timeseries",
     "description": "To ensure you're hitting this target for most of your users, we recommend measuring the 75th percentile of page loads, segmented across mobile and desktop devices.",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 11 },
     "targets": [
      {
       "expr": "quantile(0.75, Web_Vitals{name=\"CLS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CLS Data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "Web_Vitals{name=\"CLS\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}